### ISSUE TITLE
ImportError: No module named 'secrets'

### ISSUE THREAD

**Issue by midwesttech** [CommunityHoneyNetwork/chn-quickstart#4]
It appears that the guided_docker_compose.py script may have an issue.  I am receiving this error after a new install, following the quickstart directions:

    /opt/chnserver$ sudo ./guided_docker_compose.py
    Traceback (most recent call last):
      File "./guided_docker_compose.py", line 7, in <module>
        import secrets
    ImportError: No module named `'secrets'

**Comment by midwesttech** [comment]
> 
> 
> It appears that the guided_docker_compose.py script may have an issue. I am receiving this error after a new install, following the quickstart directions:
> 
> ```
> /opt/chnserver$ sudo ./guided_docker_compose.py
> Traceback (most recent call last):
>   File "./guided_docker_compose.py", line 7, in <module>
>     import secrets
> ImportError: No module named `'secrets'
> ```

If I change the first line of the guided_docker_compose.py script to use python3.6, I get past the error above.  However, then an issue appears with the validators module, which only supports up to python3.5:  https://validators.readthedocs.io/en/latest/  

```Here is the validator error:
    # ./guided_docker_compose.py
    Traceback (most recent call last):
      File "./guided_docker_compose.py", line 6, in <module>
        import validators
    ModuleNotFoundError: No module named 'validators'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'
    Original exception was:
    Traceback (most recent call last):
      File "./guided_docker_compose.py", line 6, in <module>
        import validators
    ModuleNotFoundError: No module named 'validators'```

**Comment by drewstinnett** [comment]
Hi @midwesttech, sorry for the delayed response here!  Can you try doing:

```
 $ pip3 install -r ./requirements.txt
```

I'm using python3.7, and the validators package seems to work just fine.  If that doesn't work, can you shoot me the versions you have installed?  Thanks!

**Comment by JesseBowling** [comment]
CLosing due to age
